name: Swift

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: make setup
    - name: Run tests
      run: make test
